### ISSUE TITLE
Global shortcuts are not working (95% of the time) on Windows (2 different PCs).

### ISSUE THREAD

**Issue by AlpSantoGlobalMomentumLLC** [braden-w/whispering#500]
Global shortcuts are not working on Windows 11.
Some time it is working for a moment, but most of the time not at all (99,5% of the time).
I did use different shortcut combinations. No one did work.
My existing Installation and a fresh installation, at the pc of my dad.

**Comment by rkhrkh** [comment]
Try to **avoid maximizing the application windows** when using Whispering. When the window is maximized, I often experience issues with shortcut keys not responding properly.

A useful workaround is to manually resize the application window by dragging it to fill most of the screen, without actually maximizing it. This keeps the window technically unmaximized, which allows the shortcuts to function correctly.

These shortcut-related issues tend to occur specifically when the window is maximized. I encountered this behavior on macOS.

**Comment by AlpSantoGlobalMomentumLLC** [comment]
Thank you. I did an downgrade to v6.4.2 and hope for an fix

**Comment by DavidGP** [comment]
Same here. I have massive problems with getting shortcuts to work. I can't even delete my toggle shortcut. Even if it is deleted, it still works. Instead, I'd rather use "push to talk", but whatever I try and use there, either it's not registered or when it is, it doesn't work.

I actually have completely stopped using Whispering for some months now, and use Whispertyping instead, mostly because of these ongoing massive issues with the shortcuts.

**Comment by braden-w** [comment]
@DavidGP @AlpSantoGlobalMomentumLLC @rkhrkh thank you all for the feedback, this is my number one priority this week! Hope to have a fix for shortcuts in the next few days, then pasting after.

**Comment by braden-w** [comment]
Hey everyone, so sorry for the delay! Just wanted to say I'm still working on this; ended up going down a rabbit hole in this implementation that led to overhaul the inner workings of Whispering and make some pull requests against the [TanStack query](https://github.com/TanStack/query/) library. I am still working on it!

**Comment by braden-w** [comment]
Hey everyone,

Good news! I'm almost ready to launch a new release that should resolve the shortcut issues. I've rearchitected the shortcut logic, and it should now register correctly.

Expect the new version to drop by this Friday!

Thanks for your patience with the delays. The v7 rewrite involved extensive work on the API services, which led to some unexpected challenges (it was like playing whack-a-mole). This new version, however, should address the problems you've been experiencing. Please send any feedback my way!

**Comment by VStankoV** [comment]
@braden-w Just discovered this wonderful app on Reddit 🤩
I'm on version v7.0.1 on macOS and this bug is the only thing that stops me from daily use of this wonderful app.
You probably already know this but when you minimize the app it doesn't track the hotkeys correctly and any hotkey shows notification that settings are updated and recording mode is changed but nothing actually is changed and when you open the minimized window it starts recording immediately

**Comment by DavidGP** [comment]
Hi Braden, 
While the push-to-talk hotkey is working almost perfectly now, I'm still encountering an issue when the hotkey is pressed very briefly, such as accidentally. In these cases, Whispering seems to get out of sync and malfunctions. Instead of immediately deactivating as expected, Whispering remains active. 

Specifically, I've observed the following: 

- Multiple bubble notifications appear rapidly in the bottom right corner of the screen within fractions of a second.
- The push-to-talk state can get stuck in the "on" position, making it impossible to deactivate correctly using the hotkey.
- Occasionally, strange special characters are output into the text field. 
- This seems to be triggered by very short, e.g. accidental keypresses of the push-to-talk hotkey. 

Thanks for looking into this!

**Comment by braden-w** [comment]
This has now been finally (hopefully) solved in #621 and released in [v7.2.0](https://github.com/epicenter-so/epicenter/releases/tag/v7.2.0)! Please see the response I linked [here](https://github.com/epicenter-so/epicenter/issues/491#issuecomment-3179750867) for more details. Please open another issue if the issue persists!

PS: I've also recently created a Discord group, and I'd love for you to join! You can ping me directly and get extra support there.

https://discord.gg/YWa5YVUSxa

**Comment by DavidGP** [comment]
> While the push-to-talk hotkey is working almost perfectly now, I'm still encountering an issue when the hotkey is pressed very briefly, such as accidentally. In these cases, Whispering seems to get out of sync and malfunctions. Instead of immediately deactivating as expected, Whispering remains active.

This is, unfortunately, still unresolved in version 7.2.1. I'm still using an AutoHotkey workaround that sets the minimum time the Push-to-Talk hotkey is pressed to 1 second.
